const students=[
 {id:"101234",name:"أحمد محمد علي",grade:"الأول الثانوي",group:"A",teacher:"أ. أحمد",phone:"01012345678",parent:"01112345678",attendance:94,solution:"الثلاثاء",points:460,exam:91},
 {id:"101235",name:"محمد خالد حسن",grade:"الأول الثانوي",group:"A",teacher:"أ. أحمد",phone:"01023456789",parent:"01123456789",attendance:88,solution:"الأحد",points:395,exam:84},
 {id:"301234",name:"محمود إبراهيم",grade:"الثالث الثانوي",group:"B",teacher:"أ. يحيى",phone:"01034567890",parent:"01134567890",attendance:97,solution:"الخميس",points:510,exam:96},
 {id:"301235",name:"عمر ياسر",grade:"الثالث الثانوي",group:"B",teacher:"أ. يحيى",phone:"01045678901",parent:"01145678901",attendance:82,solution:"الثلاثاء",points:350,exam:78}
];
const teachers=[
 {name:"أ. أحمد",subject:"أحياء",groups:"A",phone:"01000000001",permissions:"طلاب، حضور، امتحانات، شات"},
 {name:"أ. يحيى",subject:"أحياء",groups:"B",phone:"01000000002",permissions:"طلاب، حضور، امتحانات"}
];
let page="dashboard";
const titles={dashboard:["لوحة التحكم","نظرة سريعة على النظام"],students:["الطلاب","إدارة بيانات الطلاب والحسابات"],teachers:["المعلمين","إدارة المعلمين والصلاحيات"],groups:["المجموعات","المجموعات ومواعيد الحضور"],attendance:["الحضور","تسجيل ومتابعة الحضور"],exams:["الامتحانات","الدرجات والتقييمات"],messages:["المحادثات","شات الطلاب مع المعلمين"],notifications:["الإشعارات","إرسال التنبيهات للطلاب"],reports:["التقارير","تقارير الأداء والحضور"],settings:["الإعدادات","إعدادات النظام والحسابات"]};

document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
document.getElementById("logout").onclick=()=>alert("هذه نسخة واجهة تجريبية. اربط Authentication قبل الاستخدام الفعلي.");

function render(){document.getElementById("pageTitle").textContent=titles[page][0];document.getElementById("pageSub").textContent=titles[page][1];const c=document.getElementById("content");c.innerHTML=pages[page]();if(page==="students")bindStudentSearch();}
function pages(){return{dashboard:dashboard,students:studentsPage,teachers:teachersPage,groups:groupsPage,attendance:attendancePage,exams:examsPage,messages:messagesPage,notifications:notificationsPage,reports:reportsPage,settings:settingsPage}[page]()}
function dashboard(){return `<div class="stats">
<div class="card stat"><div><small>إجمالي الطلاب</small><strong>248</strong></div><div class="icon">👥</div></div>
<div class="card stat"><div><small>المعلمين</small><strong>12</strong></div><div class="icon">👨‍🏫</div></div>
<div class="card stat"><div><small>حضور اليوم</small><strong>91%</strong></div><div class="icon">✓</div></div>
<div class="card stat"><div><small>الامتحانات</small><strong>18</strong></div><div class="icon">📝</div></div></div>
<div class="grid2"><div class="card"><div class="section-head"><h2>أداء الحضور خلال الأسبوع</h2><span class="badge green">ممتاز</span></div><div class="chart"><div class="bar" style="height:82%"><span>السبت</span></div><div class="bar" style="height:91%"><span>الأحد</span></div><div class="bar" style="height:87%"><span>الاثنين</span></div><div class="bar" style="height:94%"><span>الثلاثاء</span></div><div class="bar" style="height:89%"><span>الأربعاء</span></div><div class="bar" style="height:96%"><span>الخميس</span></div></div></div>
<div class="card"><div class="section-head"><h2>أحدث الطلاب</h2><button class="btn secondary" onclick="page='students';render()">عرض الكل</button></div>${students.slice(0,3).map(s=>studentMini(s)).join("")}</div></div>
<div class="card" style="margin-top:18px"><div class="section-head"><h2>تقييم الأداء الشهري</h2></div><div class="cards3"><div class="kpi">متوسط الحضور<strong>91%</strong></div><div class="kpi">متوسط الامتحانات<strong>87%</strong></div><div class="kpi">إجمالي نقاط الطلاب<strong>42,850</strong></div></div></div>`}
function studentMini(s){return `<div class="student-row" style="padding:9px 0;border-bottom:1px solid var(--line)"><span class="mini">${s.name[0]}</span><div><b>${s.name}</b><small style="display:block;color:var(--muted)">${s.id} · ${s.group}</small></div><span style="margin-right:auto" class="badge">${s.attendance}% حضور</span></div>`}
function studentsPage(){return `<div class="card"><div class="section-head"><h2>قائمة الطلاب</h2><button class="btn" onclick="addStudent()">+ إضافة طالب</button></div><div class="searchbar"><input id="studentSearch" placeholder="ابحث بالاسم أو ID أو رقم الهاتف..."></div><div class="table-wrap"><table class="table"><thead><tr><th>الطالب</th><th>ID</th><th>الصف</th><th>المجموعة</th><th>الحضور</th><th>النقاط</th><th>الإجراءات</th></tr></thead><tbody id="studentBody">${studentRows(students)}</tbody></table></div></div>`}
function studentRows(arr){return arr.map(s=>`<tr><td><div class="student-row"><span class="mini">${s.name[0]}</span><b>${s.name}</b></div></td><td>${s.id}</td><td>${s.grade}</td><td>${s.group}</td><td><b>${s.attendance}%</b><div class="progress"><i style="width:${s.attendance}%"></i></div></td><td><span class="badge orange">${s.points} نقطة</span></td><td><div class="actions"><button class="btn secondary" onclick='studentPDF(${JSON.stringify(s)})'>PDF</button><button class="btn secondary" onclick='viewStudent(${JSON.stringify(s)})'>بيانات</button></div></td></tr>`).join("")}
function bindStudentSearch(){const i=document.getElementById("studentSearch");if(i)i.oninput=()=>document.getElementById("studentBody").innerHTML=studentRows(students.filter(s=>(s.name+s.id+s.phone).includes(i.value.trim())))}
function teachersPage(){return `<div class="card"><div class="section-head"><h2>المعلمين</h2><button class="btn" onclick="simpleAdd('معلم')">+ إضافة معلم</button></div><div class="table-wrap"><table class="table"><thead><tr><th>المعلم</th><th>المادة</th><th>المجموعات</th><th>الهاتف</th><th>الصلاحيات</th><th>إجراء</th></tr></thead><tbody>${teachers.map(t=>`<tr><td><b>${t.name}</b></td><td>${t.subject}</td><td>${t.groups}</td><td>${t.phone}</td><td>${t.permissions}</td><td><button class="btn secondary" onclick='editTeacher(${JSON.stringify(t)})'>تعديل الصلاحيات</button></td></tr>`).join("")}</tbody></table></div></div>`}
function groupsPage(){return `<div class="cards3"><div class="card"><span class="badge">الأول الثانوي</span><h2>مجموعة A</h2><p>أ. أحمد · السبت والثلاثاء · 12:00</p><b>32 طالب</b></div><div class="card"><span class="badge">الثالث الثانوي</span><h2>مجموعة B</h2><p>أ. يحيى · الأحد والأربعاء · 4:00</p><b>28 طالب</b></div><div class="card"><span class="badge">حصة الحل</span><h2>النظام الأسبوعي</h2><p>الأحد / الثلاثاء / الخميس</p><b>يوم واحد لكل طالب</b></div></div>`}
function attendancePage(){return `<div class="card"><div class="section-head"><h2>كشف الحضور</h2><button class="btn" onclick="alert('تم حفظ كشف الحضور التجريبي')">حفظ الحضور</button></div><div class="notice">حصة الحل تظهر للطالب في اليوم المسجل له فقط. يمكنك تعديل السجل من صلاحيات الإدارة.</div><table class="table" style="margin-top:12px"><thead><tr><th>الطالب</th><th>المجموعة</th><th>اليوم</th><th>الحالة</th><th>النسبة</th></tr></thead><tbody>${students.map(s=>`<tr><td>${s.name}</td><td>${s.group}</td><td>${s.solution}</td><td><select><option>حاضر</option><option>غائب</option></select></td><td>${s.attendance}%</td></tr>`).join("")}</tbody></table></div>`}
function examsPage(){return `<div class="card"><div class="section-head"><h2>الامتحانات</h2><button class="btn" onclick="simpleAdd('امتحان')">+ إضافة امتحان</button></div><div class="cards3"><div class="card"><span class="badge">أحياء</span><h3>اختبار الدعامة</h3><p>50 درجة · متوسط المجموعة 88%</p></div><div class="card"><span class="badge">أحياء</span><h3>اختبار التنسيق</h3><p>40 درجة · متوسط المجموعة 84%</p></div><div class="card"><span class="badge">مراجعة</span><h3>اختبار شامل</h3><p>60 درجة · التقييم قيد الاعتماد</p></div></div></div>`}
function messagesPage(){return `<div class="grid2"><div class="card"><div class="section-head"><h2>المحادثات</h2><span class="badge red">3 جديدة</span></div>${students.map(s=>`<div class="student-row" style="padding:12px 0;border-bottom:1px solid var(--line)"><span class="mini">${s.name[0]}</span><div><b>${s.name}</b><small style="display:block;color:var(--muted)">آخر رسالة منذ ساعتين</small></div><button class="btn secondary" style="margin-right:auto" onclick="chat('${s.name}')">فتح</button></div>`).join("")}</div><div class="card"><h2>شات الطالب ↔ المدرس</h2><div class="empty">اختر طالبًا لبدء المحادثة</div></div></div>`}
function notificationsPage(){return `<div class="card"><div class="section-head"><h2>إرسال إشعار</h2></div><div class="form"><label>المستلم<select><option>كل الطلاب</option><option>مجموعة A</option><option>طالب محدد</option></select></label><label>عنوان الإشعار<input placeholder="مثال: موعد امتحان"></label><label>الرسالة><textarea rows="4" placeholder="اكتب نص الإشعار"></textarea></label><button class="btn" onclick="alert('تم إرسال الإشعار التجريبي')">إرسال الإشعار</button></div></div>`}
function reportsPage(){return `<div class="stats"><div class="card"><span class="kpi">متوسط الحضور</span><strong>91%</strong></div><div class="card"><span class="kpi">متوسط الامتحانات</span><strong>87%</strong></div><div class="card"><span class="kpi">طلاب الشهر</span><strong>18</strong></div><div class="card"><span class="kpi">نقاط مكتسبة</span><strong>42,850</strong></div></div><div class="card"><h2>نظام النقاط</h2><p>الحضور، الامتحانات، النشاط وتقييم الأداء الشهري يمكن ضبط أوزانها من إعدادات النظام.</p></div>`}
function settingsPage(){return `<div class="grid2"><div class="card"><h2>إعدادات الحساب</h2><div class="form"><label>اسم المدير<input value="المدير"></label><label>رقم الهاتف<input value="01000000000"></label><button class="btn">حفظ البيانات</button><button class="btn secondary" onclick="changePassword()">تغيير كلمة المرور</button></div></div><div class="card"><h2>خط الموقع</h2><div class="notice">يمكن رفع خط woff/woff2/ttf/otf وتطبيقه على الموقع. في النسخة المتصلة بقاعدة البيانات سيتم حفظ الخط في Storage ليظهر لكل المستخدمين.</div><div class="form" style="margin-top:14px"><label>رفع خط جديد<input type="file" accept=".woff,.woff2,.ttf,.otf" id="fontFile"></label><button class="btn" onclick="applyFont()">رفع وتطبيق الخط</button></div></div></div><div class="card" style="margin-top:18px"><h2>إعدادات النظام</h2><div class="cards3"><div class="kpi">ID الأول الثانوي<strong>10XXXX</strong></div><div class="kpi">ID الثالث الثانوي<strong>30XXXX</strong></div><div class="kpi">Password الطالب<strong>آخر 6 أرقام من الهاتف</strong></div></div><div class="notice" style="margin-top:15px">الطالب لا يغير كلمة المرور. المدير فقط يستطيع إعادة تعيينها. المعلم والمدير يستطيعان تغيير كلمة مرورهما.</div></div>`}
function addStudent(){openModal(`<h2>إضافة طالب</h2><div class="form"><div class="form-grid"><label>الاسم بالكامل<input id="n" placeholder="اسم الطالب"></label><label>رقم الهاتف<input id="p" placeholder="01xxxxxxxxx"></label><label>رقم ولي الأمر<input placeholder="01xxxxxxxxx"></label><label>الصف<select><option>الأول الثانوي</option><option>الثالث الثانوي</option></select></label><label>المجموعة<input placeholder="A"></label><label>رقم الجلوس (اختياري)<input></label></div><div class="notice">سيتم إنشاء Student ID تلقائيًا، وكلمة المرور الافتراضية = آخر 6 أرقام من رقم هاتف الطالب.</div><button class="btn" onclick="alert('تم إنشاء الطالب تجريبيًا');closeModal()">حفظ الطالب</button></div>`)}
function simpleAdd(type){openModal(`<h2>إضافة ${type}</h2><div class="form"><input placeholder="الاسم"><input placeholder="التفاصيل"><button class="btn" onclick="alert('تم الحفظ تجريبيًا');closeModal()">حفظ</button></div>`)}
function viewStudent(s){openModal(`<h2>${s.name}</h2><div class="cards3"><div class="kpi">ID<strong>${s.id}</strong></div><div class="kpi">الحضور<strong>${s.attendance}%</strong></div><div class="kpi">النقاط<strong>${s.points}</strong></div></div><p><b>الصف:</b> ${s.grade}<br><b>المجموعة:</b> ${s.group}<br><b>المعلم:</b> ${s.teacher}<br><b>الهاتف:</b> ${s.phone}<br><b>ولي الأمر:</b> ${s.parent}<br><b>حصة الحل:</b> ${s.solution}<br><b>متوسط الامتحانات:</b> ${s.exam}%</p><button class="btn" onclick='studentPDF(${JSON.stringify(s)})'>تحميل PDF</button>`)}
function studentPDF(s){const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>بيان الطالب</title><style>body{font-family:Arial;padding:35px;color:#172033}h1{text-align:center}table{width:100%;border-collapse:collapse;margin-top:20px}td{border:1px solid #ddd;padding:10px}.head{background:#f2f4f8;font-weight:bold}</style></head><body><h1>بيان الطالب</h1><p style="text-align:center">EduCenter</p><table>${[['اسم الطالب',s.name],['Student ID',s.id],['الصف',s.grade],['المجموعة',s.group],['المعلم',s.teacher],['رقم الهاتف',s.phone],['رقم ولي الأمر',s.parent],['حصة الحل',s.solution],['نسبة الحضور',s.attendance+'%'],['متوسط الامتحانات',s.exam+'%'],['إجمالي النقاط',s.points]].map(x=>`<tr><td class="head">${x[0]}</td><td>${x[1]}</td></tr>`).join('')}</table><p style="margin-top:30px">تم استخراج البيان بتاريخ ${new Date().toLocaleDateString('ar-EG')}</p><script>window.print()<\/script></body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close()}
function editTeacher(t){openModal(`<h2>تعديل صلاحيات ${t.name}</h2><div class="form">${['مشاهدة الطلاب','إضافة وتعديل الطلاب','الحضور','الامتحانات والدرجات','المحادثات','التقارير'].map(x=>`<label><input type="checkbox" checked> ${x}</label>`).join('')}<button class="btn" onclick="closeModal()">حفظ الصلاحيات</button></div>`)}
function chat(name){openModal(`<h2>محادثة مع ${name}</h2><div class="notice">هذه واجهة تجريبية. عند ربط قاعدة البيانات تصبح المحادثة فورية.</div><div class="form" style="margin-top:12px"><textarea rows="4" placeholder="اكتب رسالتك..."></textarea><button class="btn">إرسال</button></div>`)}
function changePassword(){openModal(`<h2>تغيير كلمة المرور</h2><div class="form"><input type="password" placeholder="كلمة المرور الحالية"><input type="password" placeholder="كلمة المرور الجديدة"><input type="password" placeholder="تأكيد كلمة المرور"><button class="btn" onclick="closeModal()">تحديث</button></div>`)}
function applyFont(){const f=document.getElementById('fontFile').files[0];if(!f)return alert('اختر ملف الخط أولًا');const r=new FileReader();r.onload=e=>{const ff=new FontFace('CustomUploaded',e.target.result);ff.load().then(x=>{document.fonts.add(x);document.body.style.fontFamily='CustomUploaded, Arial';alert('تم تطبيق الخط على هذه الصفحة تجريبيًا. للحفظ الدائم يجب ربط Storage.');})};r.readAsArrayBuffer(f)}
function openModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
render();
